### ISSUE TITLE
What are the differences between DanKu and similar protocols?

### ISSUE THREAD

**Issue by mostafachatillon** [algorithmiaio/danku#6]
For example this one  Pandoraboxchain https://medium.com/pandoraboxchain/world-decentralized-ai-on-blockchain-with-cognitive-mining-and-open-markets-for-data-and-algorithms-4e192554024a

Or Neuromation: https://platform.neuromation.io

Probably many others

**Comment by besirkurtulmus** [comment]
@mostafachatillon Good question.

For `Pandoraboxchain`:

1. It looks like it uses reputation part of their mechanism for exchanging newly trained models. DanKu does not require a repuation system to function since it's a trustless protocol.
2. Generally most other approaches do the computation off-chain, or on another chain completely. DanKu works completely on the main-chain.
3. In the white paper, it doesn't really explain why the number of validators, and percentages were selected. The DanKu white paper does an analysis on the selected values.
4. In stage 4 they're talking about: `Launching into space a network of satellites on which AI computing will be processed`. That's a bit too ambitious for DanKu at the moment. 😅

For `Neuromation`:
1. Their white paper is in 5 different languages, which I think is pretty cool! DanKu is only in English.
2. Training is part of the Neuromation platform. In DanKu, training is done completely offline, and the blockchain is used to verify the accuracy of the given model.
3. Neuromation is also involved in generating datasets, whereas DanKu is only a protocl for exchanging ML models.
4. Neuromation is also involved in exchanging datasets in their respective marketplace. This is not a feature of DanKu.

General differences between DanKu and other approaches:

1. The DanKu white paper does not talk about tokens, or an ICO. It's a purely a technical paper. It discusses various approaches taken, and tries to tackle the single problem of creating a trustless protocol for exchanging ML models on a turing-complete blockchain.
2. DanKu was also released with a proof-of-concept competition to show-case the protocol. This is significantly different than most other approaches where a lot of theoretical applications are talked about, but no implementations are provided with their initial release. (A lot of talk, but little to no show)
3. The approach in DanKu is a lot more similar to Bitcoin's initial approach. Start with the initial core tech, and expand from there.

**Comment by besirkurtulmus** [comment]
Closing issue since there hasn't been a comment on it in the last 7 days.
